site_name: PainterQB.jl
site_description: PainterQB.jl for qubit measurement

repo_url: https://github.com/ajkeller34/PainterQB.jl/

pages:
- Home: 'index.md'
- Overview:
    - 'Design': 'design.md'
    - 'Implementation': 'implementation.md'
- API:
    - 'Index': 'api/api.md'
    - 'PainterQB': 'api/PainterQB.md'
    - 'E8257D': 'api/E8257D.md'
    - 'E5071C': 'api/E5071C.md'
    - 'AWG5014C': 'api/AWG5014C.md'
    - 'AlazarTech': 'api/AlazarTech.md'
- Miscellaneous:
    - 'Release notes': 'releases.md'
    - 'License': 'LICENSE.md'
