site_name: PainterQB.jl
site_description: PainterQB.jl for qubit measurement

repo_url: https://github.com/ajkeller34/Instruments.jl/

pages:
- Home: 'index.md'
- Overview:
    - 'Design': 'design.md'
    - 'Implementation': 'implementation.md'
- About:
    - 'Release notes': 'releases.md'
    - 'License': '../LICENSE.md'

markdown_extensions: [codehilite]
