site_name:        InstrumentControl.jl
repo_url:         https://github.com/PainterQubits/InstrumentControl.jl
site_description: Package for instrument control and superconducting qubit measurement.
site_author:      Andrew Keller

theme: material
extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Overview:
    - 'Design': design.md
    - 'Implementation': implementation.md
- Instruments:
    - 'Alazar digitizers': Alazar.md
    - Waveform generators:
        - 'AWG5014C': waveform_generator/awg5014c.md
    - VNAs:
        - 'VNAs': vna/vna.md
        - 'E5071C': vna/e5071c.md
- Miscellaneous:
    - 'Documentation building': docbuild.md
    - 'Release notes': releases.md
    - 'License': LICENSE.md
